PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS personas (persona_id TEXT PRIMARY KEY, slug TEXT UNIQUE NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS observations (observation_id TEXT PRIMARY KEY, timestamp TEXT NOT NULL, persona_id TEXT NOT NULL REFERENCES personas(persona_id), source_type TEXT NOT NULL, source_url TEXT NOT NULL, source_date TEXT, date_accessed TEXT, observation TEXT NOT NULL, problem_language TEXT, current_workaround TEXT, evidence_strength INTEGER NOT NULL CHECK(evidence_strength BETWEEN 1 AND 5), researcher_agent TEXT NOT NULL, confidence INTEGER NOT NULL CHECK(confidence BETWEEN 0 AND 100), candidate_problem_cluster TEXT, notes TEXT);
CREATE TABLE IF NOT EXISTS problems (problem_id TEXT PRIMARY KEY, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, persona_id TEXT NOT NULL REFERENCES personas(persona_id), problem_statement TEXT NOT NULL, job_to_be_done TEXT NOT NULL, description TEXT NOT NULL, evidence_strength INTEGER NOT NULL CHECK(evidence_strength BETWEEN 1 AND 5), confidence_score INTEGER CHECK(confidence_score BETWEEN 0 AND 100), status TEXT NOT NULL, date_last_validated TEXT, notes TEXT);
CREATE TABLE IF NOT EXISTS problem_sources (problem_id TEXT REFERENCES problems(problem_id), observation_id TEXT REFERENCES observations(observation_id), PRIMARY KEY(problem_id, observation_id));
CREATE TABLE IF NOT EXISTS opportunities (opportunity_id TEXT PRIMARY KEY, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, persona_id TEXT NOT NULL REFERENCES personas(persona_id), problem_id TEXT NOT NULL REFERENCES problems(problem_id), opportunity_name TEXT NOT NULL, one_sentence_pitch TEXT NOT NULL, opportunity_score REAL NOT NULL CHECK(opportunity_score BETWEEN 0 AND 100), confidence INTEGER NOT NULL CHECK(confidence BETWEEN 0 AND 100), current_stage TEXT NOT NULL, next_test TEXT NOT NULL, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS opportunity_scores (opportunity_id TEXT REFERENCES opportunities(opportunity_id), score REAL NOT NULL CHECK(score BETWEEN 0 AND 100), date TEXT NOT NULL, agent TEXT NOT NULL, reason TEXT NOT NULL, evidence TEXT NOT NULL, previous_score REAL, PRIMARY KEY(opportunity_id, date, agent));
CREATE TABLE IF NOT EXISTS competitors (competitor_id TEXT PRIMARY KEY, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, name TEXT NOT NULL, source_url TEXT NOT NULL, date_checked TEXT NOT NULL, status TEXT NOT NULL, details_json TEXT);
CREATE TABLE IF NOT EXISTS experiments (experiment_id TEXT PRIMARY KEY, opportunity_id TEXT NOT NULL REFERENCES opportunities(opportunity_id), hypothesis TEXT NOT NULL, primary_metric TEXT NOT NULL, budget REAL NOT NULL CHECK(budget >= 0), minimum_sample_size INTEGER NOT NULL, success_threshold TEXT NOT NULL, failure_threshold TEXT NOT NULL, status TEXT NOT NULL, human_approval_required INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS experiment_results (result_id INTEGER PRIMARY KEY, experiment_id TEXT NOT NULL REFERENCES experiments(experiment_id), date_range TEXT NOT NULL, spend REAL NOT NULL, impressions INTEGER NOT NULL, clicks INTEGER NOT NULL, visitors INTEGER NOT NULL, signups INTEGER NOT NULL, purchases INTEGER NOT NULL, revenue REAL NOT NULL, result TEXT NOT NULL, confidence INTEGER NOT NULL CHECK(confidence BETWEEN 0 AND 100), recommended_action TEXT NOT NULL, details_json TEXT);
